logout:
    path: /logout

login_check:
    path: /login-check

app_oauth:
    resource: "@OAuthBundle/Controller"
    type: annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

app:
    resource: "@AppBundle/Controller"
    type: annotation
