logout:
    path: /logout

login_check:
    path: /login-check

app_oauth:
    resource: "@OAuthBundle/Controller"
    type: annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

bazinga_js_translation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    prefix: /js

app:
    resource: "@AppBundle/Controller"
    type: annotation

api_v0:
    resource: "@AppBundle/Controller/V0"
    type: annotation
    prefix: /api/{_locale}/V0
    requirements: { "_locale": "fr|en" }
    defaults: { "_locale": "%locale%" }