security:
    providers:
        user_provider:
            entity:
                class:    AppBundle\Entity\User
                property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            iterations: 5

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false

        api:
            pattern:    ^/api/user
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        oauth_authorize:
            pattern:   ^/
            context:   main
            anonymous: true
            provider:  user_provider
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: app_home
            logout:
                path:   logout
                target: login
            remember_me:
                secret:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     home

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgotten-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/oauth/v2/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v0/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_REMEMBERED ] }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
